### PR TITLE
fix: prevent timeouts on Node 19+

### LINKED ISSUE #362: Disable HTTP Agent Timeout By Default
Starting with Node 19, the [`globalAgent`](https://nodejs.org/api/http.html#httpglobalagent) used by default for `http(s).request` and `http(s).get` had the socket `timeout` set to a default 5 seconds ([described here](https://nodejs.org/api/http.html#class-httpagent)).

Without getting too into the weeds of how Node is implemented, with the way the [event loop](https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick) orders timer and I/O operations, combined with [ESLint's core being synchronous in design](https://github.com/eslint/eslint/issues/15394) (until the v10 rewrite), and the socket timeout timer starting *immediately* when the socket is made... ESLint on a large project or with many plugins enabled ends up consuming the entire CPU time and the socket never actually establishes a connection before timing out.

This is what led to #323 suddenly being an issue; it was less about how long our timeout is set for and more about the 5 second default timeout on the socket itself being triggered and causing our handler to trigger eroneously.

Luckily, you had great foresight with the `settings.http.requestOptions` setting! This can be worked around trivially by adding the following to your ESLint config:

```js
settings: {
    http: {
        requestOptions: {
            agent: false,
        },
    },
}
```

A proper fix would involve updating [`parseUrlAndOptions`](https://github.com/ota-meshi/eslint-plugin-json-schema-validator/blob/main/src/utils/http-client/get-modules/http.ts#L67) with that setting as the default.

### PR DESCRIPTION
**Pull request by Kenneth-Sills**
Closes #362

### CODE REVIEW

File: src/utils/http-client/get-modules/http.ts [hunk 1]
```diff
@@ -76,6 +76,7 @@ function parseUrlAndOptions(urlStr: string, baseOptions: RequestOptions) {
     protocol: url.protocol,
     hostname,
     path: `${url.pathname || ""}${url.search || ""}`,
+    agent: false,
```
Comment (ota-meshi) [inline src/utils/http-client/get-modules/http.ts:79]: I think options should be able to be overridden.

```js
  const options: RequestOptions = {
    agent: false,
    ...baseOptions,
    protocol: url.protocol,
    hostname,
    path: `${url.pathname || ""}${url.search || ""}`,
```

**Review by ota-meshi — CHANGES_REQUESTED** [review]

File: src/utils/http-client/get-modules/http.ts (hunk 1 above)
Comment (Kenneth-Sills) [reply src/utils/http-client/get-modules/http.ts]: Ah, of course! Thank you.

**Review by ota-meshi — APPROVED** [review]
Thank you very much!
